---
- name: tomcatdeploy-playbook-name
  hosts: clouderanodes

  tasks:

      - name: install the latest version of Tomcat
        yum:
          name: tomcat
          state: latest

      - name: install OpenJDK 1.8.0
        yum:
          name: java-1.8.0-openjdk
          state: present

      - name: ensure a list of Tomcat packages installed
        yum:
          name: "{{ packages }}"
          state: latest
        vars:
          packages:
            - tomcat-webapps
            - tomcat-admin-webapps

      - name: Install base packages
        yum: name={{ item }} state=installed
        with_items:
            - ntp
            - htop
        tags:
            - packages

      - name: Upgrade pip
        pip: name=pip state=latest
        tags:
            - packages

      - name: Start and enable Tomcat service
        systemd:
          name: tomcat
          state: started
          enabled: true
          daemon_reload: true

      - name: Create user
        user:
           name: "deploy_user"
           comment: "Used to deploy Tomcat"
           state: present

      - name: Create .ssh folder
        file:
          path: "/home/deploy_user/.ssh/"
          state: directory
          mode: 0755
