---
- hosts: clouderanodes

  tasks:

      - name: install the latest version of Tomcat
        yum:
          name: tomcat
          state: latest


      - name: ensure a list of Tomcat packages installed
        yum:
          name: "{{ packages }}"
        vars:
          packages:
            - tomcat-webapps
            - tomcat-admin-webapps

      - name: Install base packages
        yum: name={{ item }} state=installed
        with_items:
            - locales
            - build-essential
            - acl
            - ntp
            - htop
            - git
            - supervisor
            - python-pip
            - python3-pip
        tags:
            - packages

      - name: Upgrade pip
        pip: name=pip state=latest
        tags:
            - packages

      - name: Create user
        user:
           name: "deploy_user"
           comment: "Used to deploy Tomcat"
           state: present
      - name: Create .ssh folder
        file:
          path: "/home/deploy_user/.ssh/"
          state: directory
          mode: 0755
